name: test
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - run: npm run test